//! # 🛑 Intersection Module
//!
//! Detects stop sign proximity, deceleration compliance, and intersection
//! occupancy to prevent "blocking the box" violations.
//!
//! ## Features
//!
//! - **Stop sign detection**, estimates distance via pinhole model and
//!   raises a violation alert if ego speed is too high at close range.
//! - **Blocked intersection**, measures how much of the forward view is
//!   occupied by vehicles; fires an alert if occupancy exceeds 30% while
//!   the ego vehicle is moving fast enough to enter the box.
//!
//! ## Status
//!
//! Core logic is functional.  The BEV occupancy grid and deceleration
//! profiling are placeholders, calibration with real camera extrinsics
//! will improve accuracy.

use crate::config::IntersectionConfig;
use crate::detection::yolo::Detection;
use crate::utils::geometry::estimate_distance;

// ─────────────────────────────────────────────────────────────────────────────
//  IntersectionAlert
// ─────────────────────────────────────────────────────────────────────────────

/// An alert generated by the intersection analyzer.
///
/// Two variants cover the two main violation types this module detects.
#[derive(Debug, Clone)]
pub enum IntersectionAlert {
    /// The ego vehicle is approaching a stop sign too fast.
    StopSignViolation {
        /// Confidence of the stop-sign detection (0.0 – 1.0).
        confidence: f32,

        /// Estimated distance from the camera to the stop line (meters).
        distance_to_stop_line: f32,

        /// Current ego-vehicle speed (mph) at the time of the alert.
        ego_speed: f32,
    },

    /// The intersection ahead is congested and the ego vehicle risks
    /// "blocking the box".
    BlockedIntersection {
        /// Confidence derived from occupancy percentage (0.0 – 1.0).
        confidence: f32,

        /// Percentage of the forward view occupied by vehicles (0 – 100 %).
        occupancy_pct: f32,

        /// Estimated distance to the stop line (meters).
        distance_to_stop_line: f32,

        /// Current ego-vehicle speed (mph).
        ego_speed: f32,
    },

    /// Predictive warning: the forward box is filling up fast — it will
    /// likely be blocked by the time the ego vehicle arrives, so it should
    /// not commit. Emitted when occupancy is above
    /// `filling_occupancy_threshold` and still rising faster than
    /// `occupancy_rise_rate`, but not yet past `blocked_occupancy_threshold`.
    IntersectionFilling {
        /// Smoothed forward-region occupancy (0 – 100 %).
        occupancy_pct: f32,

        /// Current rise rate of occupancy (percentage points per second).
        rise_rate_pct_s: f32,

        /// Current ego-vehicle speed (mph).
        ego_speed: f32,
    },
}

// ─────────────────────────────────────────────────────────────────────────────
//  IntersectionAnalyzer
// ─────────────────────────────────────────────────────────────────────────────

/// Forward "intersection box" region, as fractions of the frame: the centre
/// horizontal band below the horizon — i.e. the road ahead of the ego vehicle.
/// Only vehicles inside this region count toward blocked-intersection
/// occupancy, so parked cars at the far left/right edges cannot trigger the
/// alert.
const BOX_REGION_X_MIN: f32 = 0.25;
const BOX_REGION_X_MAX: f32 = 0.75;
const BOX_REGION_Y_MIN: f32 = 0.30;
const BOX_REGION_Y_MAX: f32 = 1.00;

/// Hysteresis margin (percentage points) below `blocked_occupancy_threshold`:
/// once a blocked alert is active it stays active until occupancy drops this
/// far below the threshold, preventing flicker between BLOCKED and FILLING as
/// occupancy oscillates around the boundary.
const BLOCKED_EXIT_MARGIN: f32 = 8.0;

/// Analyzes intersection safety from raw YOLO detections.
///
/// Call [`analyze()`](IntersectionAnalyzer::analyze) once per frame with the
/// current detections, ego speed, and frame delta.  The method returns a list
/// of active alerts (may be empty).
pub struct IntersectionAnalyzer {
    /// Intersection-specific thresholds (distances, speeds, grid params).
    config: IntersectionConfig,

    /// Known real-world width of a stop sign in meters.
    ///
    /// US standard stop sign diameter ≈ 30 inches ≈ 0.75 m.
    stop_sign_width_m: f32,

    /// Frame width in pixels (from camera config).
    frame_width: u32,

    /// Frame height in pixels (from camera config).
    frame_height: u32,

    /// Camera focal length in pixels (from camera config).
    focal_length: f32,

    /// Low-pass-filtered forward-region occupancy (%) from the previous
    /// frame, used to compute the occupancy rise rate for the predictive
    /// filling alert. `None` until the first frame is seen.
    prev_occupancy: Option<f32>,

    /// Whether a BLOCKED alert is currently active (hysteresis latch).
    blocked_active: bool,

    /// Smoothing factor for the occupancy low-pass filter (0.0 – 1.0).
    occupancy_alpha: f32,
}

impl IntersectionAnalyzer {
    /// Constructs a new intersection analyzer.
    ///
    /// # Parameters
    /// - `config`, The top-level pipeline config; only the
    ///   `config.intersection` subset is used.
    ///
    /// # Returns
    /// An `IntersectionAnalyzer` ready to process frames.
    pub fn new(config: &crate::config::Config, frame_width: u32, frame_height: u32) -> Self {
        Self {
            config: config.intersection.clone(),
            stop_sign_width_m: 0.75,
            frame_width,
            frame_height,
            focal_length: config.camera.focal_length,
            prev_occupancy: None,
            blocked_active: false,
            occupancy_alpha: 0.3,
        }
    }

    /// Analyzes the current frame for intersection-related alerts.
    ///
    /// # Parameters
    /// - `detections`, Raw detections from the YOLO detector for the
    ///   current frame.
    /// - `ego_speed`, Ego-vehicle speed in **miles per hour**.
    /// - `dt_secs`, Time elapsed since the previous frame (seconds).
    ///   Currently reserved for future temporal filtering.
    ///
    /// # Returns
    /// A `Vec<IntersectionAlert>`, empty if no violation conditions are met.
    ///
    /// # Alert logic (stop sign)
    /// 1. Filter detections for class_id == 0 (stop_sign).
    /// 2. Estimate distance via pinhole: `Z = (f × W) / w`.
    /// 3. If `distance < stop_sign_warning_distance` **and**
    ///    `ego_speed >= stop_sign_warning_speed`, emit `StopSignViolation`.
    ///
    /// # Alert logic (blocked intersection)
    /// 1. Filter detections for vehicle classes (3, 4, 5).
    /// 2. Measure how much of the forward "intersection box" region (centre
    ///    band of the frame, below the horizon) is covered by those vehicles.
    /// 3. If `occupancy > blocked_occupancy_threshold` **and**
    ///    `ego_speed >= blocked_intersection_speed`, emit `BlockedIntersection`.
    /// 4. Else, if occupancy is above `filling_occupancy_threshold` and still
    ///    rising faster than `occupancy_rise_rate`, emit the predictive
    ///    `IntersectionFilling` warning ("it will be blocked by the time you
    ///    get there").
    pub fn analyze(
        &mut self,
        detections: &[Detection],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<IntersectionAlert> {
        let mut alerts = Vec::new();
        self.check_stop_signs(detections, ego_speed, &mut alerts);
        self.check_blocked_intersection(detections, ego_speed, dt_secs, &mut alerts);
        alerts
    }

    /// Check for stop-sign violations: ego speed too high near a stop sign.
    fn check_stop_signs(
        &self,
        detections: &[Detection],
        ego_speed: f32,
        alerts: &mut Vec<IntersectionAlert>,
    ) {
        const MIN_CONFIDENCE: f32 = 0.5;
        for sign in detections
            .iter()
            .filter(|d| d.class_id == 0 && d.confidence >= MIN_CONFIDENCE)
        {
            let pixel_width = (sign.x2 - sign.x1).abs();
            if pixel_width < 1.0 {
                continue;
            }

            let distance =
                estimate_distance(pixel_width, self.stop_sign_width_m, self.focal_length)
                    .clamp(1.0, 200.0);

            if distance <= self.config.stop_sign_warning_distance
                && ego_speed >= self.config.stop_sign_warning_speed
            {
                alerts.push(IntersectionAlert::StopSignViolation {
                    confidence: sign.confidence,
                    distance_to_stop_line: distance,
                    ego_speed,
                });
            }
        }
    }

    /// Check for blocked intersection: the road ahead is full of vehicles.
    ///
    /// Only vehicles whose centre lies inside the forward "intersection box"
    /// region (the centre horizontal band of the frame, below the horizon)
    /// count toward occupancy, and their boxes are clipped to that region.
    /// Parked cars at the far left/right edges therefore cannot inflate the
    /// reading, so the alert reflects how packed the road *ahead* is.
    ///
    /// Two-stage logic:
    /// - occupancy already above `blocked_occupancy_threshold` →
    ///   `BlockedIntersection` (the box is full now);
    /// - occupancy above `filling_occupancy_threshold` and still rising
    ///   faster than `occupancy_rise_rate` → `IntersectionFilling`
    ///   (predictive: it will be blocked by the time the ego arrives).
    fn check_blocked_intersection(
        &mut self,
        detections: &[Detection],
        ego_speed: f32,
        dt_secs: f32,
        alerts: &mut Vec<IntersectionAlert>,
    ) {
        let vehicles: Vec<&Detection> = detections
            .iter()
            .filter(|d| (3..=5).contains(&d.class_id) && d.confidence > 0.4)
            .collect();

        let (fw, fh) = (self.frame_width as f32, self.frame_height as f32);
        let (rx1, ry1) = (fw * BOX_REGION_X_MIN, fh * BOX_REGION_Y_MIN);
        let (rx2, ry2) = (fw * BOX_REGION_X_MAX, fh * BOX_REGION_Y_MAX);
        let region_area = (rx2 - rx1) * (ry2 - ry1);

        let occupied_area: f32 = vehicles
            .iter()
            .map(|v| {
                let cx = (v.x1 + v.x2) / 2.0;
                let cy = (v.y1 + v.y2) / 2.0;
                if cx < rx1 || cx > rx2 || cy < ry1 || cy > ry2 {
                    return 0.0;
                }
                let ox1 = v.x1.max(rx1);
                let oy1 = v.y1.max(ry1);
                let ox2 = v.x2.min(rx2);
                let oy2 = v.y2.min(ry2);
                ((ox2 - ox1) * (oy2 - oy1)).max(0.0)
            })
            .sum();

        let occupancy_pct = (occupied_area / region_area * 100.0).clamp(0.0, 100.0);

        // Trend: low-pass smooth occupancy and compute the rise rate (%/s).
        let (smoothed, rise_rate) = match self.prev_occupancy {
            Some(prev) if dt_secs > 0.001 => {
                let sm = self.occupancy_alpha * occupancy_pct + (1.0 - self.occupancy_alpha) * prev;
                (sm, (sm - prev) / dt_secs)
            }
            _ => (occupancy_pct, 0.0),
        };
        self.prev_occupancy = Some(smoothed);

        if ego_speed < self.config.blocked_intersection_speed {
            return;
        }

        // Hysteresis: enter BLOCKED above the full threshold, stay active
        // until occupancy drops BLOCKED_EXIT_MARGIN below it, so the alert
        // does not flicker between BLOCKED and FILLING at the boundary.
        let enter = occupancy_pct > self.config.blocked_occupancy_threshold;
        let stay = self.blocked_active
            && occupancy_pct > self.config.blocked_occupancy_threshold - BLOCKED_EXIT_MARGIN;
        let is_blocked = enter || stay;
        self.blocked_active = is_blocked;

        if ego_speed < self.config.blocked_intersection_speed {
            return;
        }

        if is_blocked {
            alerts.push(IntersectionAlert::BlockedIntersection {
                confidence: occupancy_pct / 100.0,
                occupancy_pct,
                distance_to_stop_line: self.config.blocked_distance_to_stop,
                ego_speed,
            });
        } else if smoothed > self.config.filling_occupancy_threshold
            && rise_rate > self.config.occupancy_rise_rate
        {
            alerts.push(IntersectionAlert::IntersectionFilling {
                occupancy_pct: smoothed,
                rise_rate_pct_s: rise_rate,
                ego_speed,
            });
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    /// Helper: create a Detection with explicit fields.
    fn make_det(class_id: u32, x1: f32, y1: f32, x2: f32, y2: f32, conf: f32) -> Detection {
        Detection {
            x1,
            y1,
            x2,
            y2,
            confidence: conf,
            class_id,
        }
    }

    /// No detections → no alerts.
    #[test]
    fn test_no_alerts_with_empty_detections() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        let alerts = analyzer.analyze(&[], 0.0, 0.033);
        assert!(alerts.is_empty());
    }

    /// A stop sign is detected but ego speed is 0 → no violation.
    #[test]
    fn test_no_stop_sign_violation_when_slow() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        let dets = vec![make_det(0, 100.0, 200.0, 120.0, 240.0, 0.9)];
        let alerts = analyzer.analyze(&dets, 0.0, 0.033);
        assert!(alerts.is_empty());
    }

    /// Two large vehicles covering the forward "intersection box" region →
    /// blocked intersection alert expected.
    #[test]
    fn test_intersection_occupancy_detection() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        // Both boxes sit inside the forward region (x: 320-960, y: 216-720).
        let dets = vec![
            make_det(3, 400.0, 216.0, 800.0, 720.0, 0.9),
            make_det(3, 800.0, 216.0, 1000.0, 720.0, 0.9),
        ];
        let alerts = analyzer.analyze(&dets, 20.0, 0.033);
        let blocked = alerts
            .iter()
            .any(|a| matches!(a, IntersectionAlert::BlockedIntersection { .. }));
        assert!(blocked, "Expected BlockedIntersection alert");
    }

    /// Occupancy rising toward (but not yet past) the full threshold triggers
    /// the predictive `IntersectionFilling` warning — "it will be blocked by
    /// the time you get there".
    #[test]
    fn test_rising_occupancy_triggers_filling_alert() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        // dt = 0.1 s (10 fps). Occupancy of the forward region rises
        // 15% -> 22% -> 25% over three frames.
        let frame = |occ_pct: f32| -> Vec<Detection> {
            // region area = (960-320)*(720-216) = 322560 px
            let w = occ_pct / 100.0 * 322560.0 / 504.0;
            vec![make_det(3, 400.0, 216.0, 400.0 + w, 720.0, 0.9)]
        };

        let a1 = analyzer.analyze(&frame(15.0), 20.0, 0.1);
        assert!(a1.is_empty(), "15% occupancy must be quiet");
        let a2 = analyzer.analyze(&frame(22.0), 20.0, 0.1);
        assert!(a2.is_empty(), "smoothed occupancy still below filling threshold");
        let a3 = analyzer.analyze(&frame(25.0), 20.0, 0.1);
        assert!(
            a3.iter()
                .any(|a| matches!(a, IntersectionAlert::IntersectionFilling { .. })),
            "rising occupancy should emit the predictive filling alert"
        );
        assert!(
            a3.iter()
                .all(|a| !matches!(a, IntersectionAlert::BlockedIntersection { .. })),
            "below the full threshold there must be no BLOCKED alert"
        );
    }

    /// Once BLOCKED is active, occupancy dipping below the full threshold but
    /// above the hysteresis exit margin keeps the alert active (no flicker).
    #[test]
    fn test_blocked_alert_has_hysteresis() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        let frame = |occ_pct: f32| -> Vec<Detection> {
            let w = occ_pct / 100.0 * 322560.0 / 504.0;
            vec![make_det(3, 400.0, 216.0, 400.0 + w, 720.0, 0.9)]
        };

        let a1 = analyzer.analyze(&frame(35.0), 20.0, 0.1); // 35% > 30% → blocked
        assert!(a1.iter().any(|a| matches!(a, IntersectionAlert::BlockedIntersection { .. })));
        let a2 = analyzer.analyze(&frame(26.0), 20.0, 0.1); // dips to 26% (> 22%) → still blocked
        assert!(a2.iter().any(|a| matches!(a, IntersectionAlert::BlockedIntersection { .. })));
        let a3 = analyzer.analyze(&frame(10.0), 20.0, 0.1); // drops to 10% → cleared
        assert!(a3.is_empty());
        let a4 = analyzer.analyze(&frame(35.0), 20.0, 0.1); // back above → blocked again
        assert!(a4.iter().any(|a| matches!(a, IntersectionAlert::BlockedIntersection { .. })));
    }

    /// Large vehicles parked at the far left/right edges (outside the forward
    /// region) must NOT trigger a blocked-intersection alert.
    #[test]
    fn test_edge_parked_cars_do_not_block() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg, 1280, 720);
        // Centers at x=100 and x=1180 — both outside the region (320-960).
        let dets = vec![
            make_det(3, 0.0, 0.0, 200.0, 720.0, 0.9),
            make_det(3, 1080.0, 0.0, 1280.0, 720.0, 0.9),
        ];
        let alerts = analyzer.analyze(&dets, 20.0, 0.033);
        assert!(
            alerts
                .iter()
                .all(|a| !matches!(a, IntersectionAlert::BlockedIntersection { .. })),
            "Edge vehicles must not count toward occupancy"
        );
    }
}
