//! # 🛑 Intersection Module
//!
//! Detects stop sign proximity, deceleration compliance, and intersection
//! occupancy to prevent "blocking the box" violations.
//!
//! ## Features
//!
//! - Stop sign detection + distance estimation
//! - Ego-vehicle deceleration profiling
//! - Bird's Eye View (BEV) occupancy grid (20m ahead, 0.5m/cell)
//!
//! ## TODO
//!
//! - [ ] Implement stop-line distance estimation from bounding box
//! - [ ] Build BEV occupancy grid projection
//! - [ ] Implement "blocked intersection" logic
//! - [ ] Add alerting when ego is not decelerating
//! - [ ] Write property-based tests for occupancy math

#![allow(unused_variables, dead_code)]

use crate::detection::yolo::Detection;

/// An alert generated by the intersection analyzer.
#[derive(Debug, Clone)]
pub enum IntersectionAlert {
    StopSignViolation {
        confidence: f32,
        distance_to_stop_line: f32,
        ego_speed: f32,
    },
    BlockedIntersection {
        confidence: f32,
        occupancy_pct: f32,
        distance_to_stop_line: f32,
        ego_speed: f32,
    },
}

/// Analyzes intersection safety from detections.
pub struct IntersectionAnalyzer {
    // TODO: config, occupancy grid state
}

impl IntersectionAnalyzer {
    pub fn new(config: &crate::config::Config) -> Self {
        todo!("Initialize intersection analyzer from config");
    }

    /// Analyzes the current frame for intersection-related alerts.
    pub fn analyze(
        &mut self,
        detections: &[Detection],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<IntersectionAlert> {
        todo!("Check stop sign compliance + occupancy grid");
    }
}
