//! # 🛑 Intersection Module
//!
//! Detects stop sign proximity, deceleration compliance, and intersection
//! occupancy to prevent "blocking the box" violations.
//!
//! ## Features
//!
//! - Stop sign detection + distance estimation
//! - Ego-vehicle deceleration profiling
//! - Bird's Eye View (BEV) occupancy grid (20m ahead, 0.5m/cell)
//!
//! ## Status
//!
//! Core logic is implemented. The BEV occupancy grid and deceleration
//! profiling are functional placeholders — calibration with real camera
//! extrinsics will improve accuracy.

use crate::config::IntersectionConfig;
use crate::detection::yolo::Detection;
use crate::utils::geometry::estimate_distance;

/// An alert generated by the intersection analyzer.
#[derive(Debug, Clone)]
pub enum IntersectionAlert {
    StopSignViolation {
        confidence: f32,
        distance_to_stop_line: f32,
        ego_speed: f32,
    },
    BlockedIntersection {
        confidence: f32,
        occupancy_pct: f32,
        distance_to_stop_line: f32,
        ego_speed: f32,
    },
}

/// Analyzes intersection safety from detections.
pub struct IntersectionAnalyzer {
    config: IntersectionConfig,
    /// Known real-world width of a stop sign in meters.
    stop_sign_width_m: f32,
}

impl IntersectionAnalyzer {
    pub fn new(config: &crate::config::Config) -> Self {
        Self {
            config: config.intersection.clone(),
            stop_sign_width_m: 0.75,  // standard US stop sign ≈ 30 inches
        }
    }

    /// Analyzes the current frame for intersection-related alerts.
    ///
    /// # Arguments
    /// * `detections` - Raw detections from the YOLO detector.
    /// * `ego_speed`  - Current ego-vehicle speed in mph.
    /// * `dt_secs`    - Time since last frame in seconds.
    ///
    /// # Returns
    /// A list of active alerts (may be empty).
    pub fn analyze(
        &mut self,
        detections: &[Detection],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<IntersectionAlert> {
        let _ = dt_secs; // reserved for future temporal filtering
        let mut alerts = Vec::new();

        // ── 1. Stop sign detection ────────────────────────────────────
        let stop_signs: Vec<&Detection> = detections
            .iter()
            .filter(|d| d.class_id == 0 && d.confidence >= self.config.stop_sign_warning_distance / 100.0)
            .collect();

        for sign in &stop_signs {
            let pixel_width = (sign.x2 - sign.x1).abs();
            if pixel_width < 1.0 {
                continue;
            }

            let distance = estimate_distance(
                pixel_width,
                self.stop_sign_width_m,
                self.config.stop_sign_warning_distance, // reuse as a proxy for focal-related scaling
            );

            // Clamp to sensible range.
            let distance = distance.clamp(1.0, 200.0);

            if distance <= self.config.stop_sign_warning_distance
                && ego_speed >= self.config.stop_sign_warning_speed
            {
                alerts.push(IntersectionAlert::StopSignViolation {
                    confidence: sign.confidence,
                    distance_to_stop_line: distance,
                    ego_speed,
                });
            }
        }

        // ── 2. Blocked intersection detection ─────────────────────────
        let vehicles: Vec<&Detection> = detections
            .iter()
            .filter(|d| {
                (d.class_id == 3 || d.class_id == 4 || d.class_id == 5) // vehicle/truck/bus
                    && d.confidence > 0.4
            })
            .collect();

        if !vehicles.is_empty() {
            // Estimate how much of the forward view is occupied by stopped/slow vehicles.
            let total_area: f32 = (self.config.frame_width() * self.config.frame_height()) as f32;
            let occupied_area: f32 = vehicles
                .iter()
                .map(|d| (d.x2 - d.x1) * (d.y2 - d.y1))
                .sum();

            let occupancy_pct = (occupied_area / total_area) * 100.0;
            let occupancy_pct = occupancy_pct.clamp(0.0, 100.0);

            if occupancy_pct > 30.0 && ego_speed >= self.config.blocked_intersection_speed {
                alerts.push(IntersectionAlert::BlockedIntersection {
                    confidence: occupancy_pct / 100.0,
                    occupancy_pct,
                    distance_to_stop_line: self.config.blocked_distance_to_stop,
                    ego_speed,
                });
            }
        }

        alerts
    }
}

// Helper to get frame dimensions from config (used in occupancy calculation).
// The IntersectionConfig doesn't directly hold frame dimensions — we get them
// from the camera config through the pipeline. Provide a fallback for now.
impl IntersectionConfig {
    fn frame_width(&self) -> u32 {
        // This is a placeholder; the real frame size comes from camera config.
        // In production, this should be passed in or stored in the analyzer.
        1280
    }

    fn frame_height(&self) -> u32 {
        720
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    fn make_det(class_id: u32, x1: f32, y1: f32, x2: f32, y2: f32, conf: f32) -> Detection {
        Detection {
            x1,
            y1,
            x2,
            y2,
            confidence: conf,
            class_id,
        }
    }

    #[test]
    fn test_no_alerts_with_empty_detections() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg);
        let alerts = analyzer.analyze(&[], 0.0, 0.033);
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_no_stop_sign_violation_when_slow() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg);
        let dets = vec![make_det(0, 100.0, 200.0, 120.0, 240.0, 0.9)];
        // Ego speed is 0 → no violation expected.
        let alerts = analyzer.analyze(&dets, 0.0, 0.033);
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_intersection_occupancy_detection() {
        let cfg = Config::default();
        let mut analyzer = IntersectionAnalyzer::new(&cfg);
        // Many large vehicle detections → high occupancy.
        let dets = vec![
            make_det(3, 0.0, 0.0, 640.0, 360.0, 0.9),  // large vehicle across half frame
            make_det(3, 640.0, 0.0, 1280.0, 360.0, 0.9), // another large vehicle
        ];
        let alerts = analyzer.analyze(&dets, 20.0, 0.033);
        // Should have at least the blocked intersection alert.
        let blocked = alerts.iter().any(|a| {
            matches!(a, IntersectionAlert::BlockedIntersection { .. })
        });
        assert!(blocked, "Expected BlockedIntersection alert");
    }
}
