//! # 🚗 Lane Relative Speed Module
//!
//! Estimates relative speed of adjacent lane vehicles using camera-only
//! methods and triggers "Merge Right" reminders when the right lane
//! is moving significantly faster.
//!
//! ## Algorithm
//!
//! 1. **Lane assignment** — Each track's centroid x-coordinate is compared
//!    against three equal vertical strips (left / ego / right).
//! 2. **Distance estimation** — Pinhole model `Z = (f × W) / w`.
//! 3. **Relative velocity** — `dZ/dt` from the previous frame's distance.
//! 4. **Low-pass filter** — First-order IIR (`alpha = 0.3`) to reduce jitter.
//! 5. **Hysteresis** — The speed differential must persist for at least
//!    `hysteresis_seconds` before an alert fires.
//!
//! ## Status
//!
//! Core logic is functional.  Lane boundaries are a simple frame trisection;
//! real-world calibration (e.g. vanishing-point estimation or lane-line
//! detection) will improve accuracy.

use crate::config::LaneSpeedConfig;
use crate::tracking::deep_sort::Track;
use crate::utils::geometry::{compute_relative_velocity, estimate_distance, low_pass_filter};

// ─────────────────────────────────────────────────────────────────────────────
//  LaneSpeedAlert
// ─────────────────────────────────────────────────────────────────────────────

/// An alert generated by the lane-speed analyzer telling the driver to
/// consider merging right.
#[derive(Debug, Clone)]
pub struct LaneSpeedAlert {
    /// How many mph faster the right lane is moving compared to the ego lane.
    ///
    /// Positive values mean the right lane is faster.
    pub speed_diff_mph: f32,

    /// How many seconds the speed-differential condition has persisted
    /// without dropping below the threshold.
    pub duration_secs: f32,
}

// ─────────────────────────────────────────────────────────────────────────────
//  LaneState (private)
// ─────────────────────────────────────────────────────────────────────────────

/// Per-lane running state used for hysteresis and temporal smoothing.
#[derive(Debug, Clone, Default)]
struct LaneState {
    /// Average (raw) speed of vehicles in this lane (mph) for the current frame.
    avg_speed: f32,

    /// Low-pass-filtered speed (mph) — used for the actual alert decision.
    smoothed_speed: f32,

    /// Accumulated time (seconds) that this lane has been exceeding the
    /// speed-differential threshold.
    trigger_duration: f32,

    /// Distances (m) from the previous frame, used to compute velocity
    /// via `(d_prev - d_curr) / dt`.
    prev_distances: Vec<f32>,
}

// ─────────────────────────────────────────────────────────────────────────────
//  LaneSpeedAnalyzer
// ─────────────────────────────────────────────────────────────────────────────

/// Analyzes tracked vehicles for lane-speed differentials and emits
/// courtesy "Merge Right" alerts.
pub struct LaneSpeedAnalyzer {
    /// Lane-speed specific thresholds.
    config: LaneSpeedConfig,

    /// Frame width in pixels; used to divide the image into three lane strips.
    frame_width: f32,

    /// Known real-world width of a typical vehicle in meters (≈ 1.8 m).
    vehicle_width_m: f32,

    /// Camera focal length in pixels (from config).
    focal_length: f32,

    /// Per-lane running state: index 0 = left, 1 = ego, 2 = right.
    lanes: [LaneState; 3],

    /// Smoothing factor for the low-pass filter (0.0 – 1.0).
    /// `alpha = 0.3` means 30 % new value, 70 % previous value.
    alpha: f32,
}

impl LaneSpeedAnalyzer {
    /// Constructs a new lane-speed analyzer.
    ///
    /// # Parameters
    /// - `config` — Top-level pipeline config; uses `config.camera` for
    ///   intrinsics and `config.lane_speed` for thresholds.
    ///
    /// # Returns
    /// A ready-to-use `LaneSpeedAnalyzer`.
    pub fn new(config: &crate::config::Config) -> Self {
        Self {
            config: config.lane_speed.clone(),
            frame_width: config.camera.frame_width as f32,
            focal_length: config.camera.focal_length,
            vehicle_width_m: 1.8,
            lanes: [LaneState::default(), LaneState::default(), LaneState::default()],
            alpha: 0.3,
        }
    }

    /// Assigns a bounding box to a lane based on its centroid x-position.
    ///
    /// The frame is divided into three equal vertical strips:
    /// - `cx < width/3` → left lane (index 0)
    /// - `cx < 2×width/3` → ego lane (index 1)
    /// - otherwise → right lane (index 2)
    ///
    /// # Parameters
    /// - `bbox` — Bounding box `(x1, y1, x2, y2)` in pixels.
    ///
    /// # Returns
    /// Lane index: `0` (left), `1` (ego), or `2` (right).
    fn assign_lane(&self, bbox: &(f32, f32, f32, f32)) -> usize {
        let cx = (bbox.0 + bbox.2) / 2.0;
        let third = self.frame_width / 3.0;
        if cx < third {
            0 // left lane
        } else if cx < 2.0 * third {
            1 // ego lane
        } else {
            2 // right lane
        }
    }

    /// Analyzes tracked vehicles for lane-speed compliance.
    ///
    /// # Parameters
    /// - `tracks` — Active tracked objects from the
    ///   [`MultiObjectTracker`](crate::tracking::deep_sort::MultiObjectTracker).
    /// - `ego_speed` — Ego-vehicle speed in **mph** (fallback when no
    ///   vehicles are detected in the ego lane).
    /// - `dt_secs` — Time since the last frame (seconds).
    ///
    /// # Returns
    /// A `Vec<LaneSpeedAlert>`.  Empty means no courtesy reminder is needed.
    ///
    /// # Alert logic
    /// 1. Assign each track to a lane.
    /// 2. Estimate per-lane average speed from inter-frame distance changes.
    /// 3. Low-pass filter the speeds.
    /// 4. If `right_smoothed - ego_smoothed > speed_diff_threshold`,
    ///    accumulate `trigger_duration`; else reset it.
    /// 5. If `trigger_duration >= hysteresis_seconds`, emit an alert.
    pub fn analyze(
        &mut self,
        tracks: &[Track],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<LaneSpeedAlert> {
        let lane_dists = self.collect_lane_distances(tracks);
        self.compute_lane_speeds(&lane_dists, dt_secs);
        self.check_right_lane_faster(ego_speed, dt_secs)
    }

    /// Assign each track to a lane and estimate its distance.
    fn collect_lane_distances(&self, tracks: &[Track]) -> [Vec<f32>; 3] {
        let mut lane_dists: [Vec<f32>; 3] = [Vec::new(), Vec::new(), Vec::new()];

        for track in tracks {
            let lane = self.assign_lane(&track.bbox);
            let pixel_width = (track.bbox.2 - track.bbox.0).abs();
            if pixel_width < 2.0 {
                continue;
            }

            let distance_m =
                estimate_distance(pixel_width, self.vehicle_width_m, self.focal_length);
            if distance_m >= 0.5 && distance_m <= 200.0 {
                lane_dists[lane].push(distance_m);
            }
        }

        lane_dists
    }

    /// Update per-lane smoothed speeds from distance measurements.
    fn compute_lane_speeds(&mut self, lane_dists: &[Vec<f32>; 3], dt_secs: f32) {
        for lane_idx in 0..3 {
            let prev = &self.lanes[lane_idx].prev_distances;
            let curr = &lane_dists[lane_idx];

            let avg_speed = if !prev.is_empty() && !curr.is_empty() && dt_secs > 0.001 {
                let n = prev.len().min(curr.len());
                let total_vel: f32 = (0..n)
                    .map(|i| compute_relative_velocity(prev[i], curr[i], dt_secs))
                    .sum();
                (total_vel / n as f32) * 2.237 // m/s -> mph
            } else {
                0.0
            };

            self.lanes[lane_idx].avg_speed = avg_speed;
            self.lanes[lane_idx].smoothed_speed = low_pass_filter(
                avg_speed,
                self.lanes[lane_idx].smoothed_speed,
                self.alpha,
            );
            self.lanes[lane_idx].prev_distances = curr.to_vec();
        }
    }

    /// If the right lane is faster than the ego lane past the threshold and
    /// hysteresis, emit an alert.
    fn check_right_lane_faster(&mut self, ego_speed: f32, dt_secs: f32) -> Vec<LaneSpeedAlert> {
        let right_speed = self.lanes[2].smoothed_speed;
        let ego_lane_speed = if self.lanes[1].smoothed_speed.abs() > 0.1 {
            self.lanes[1].smoothed_speed
        } else {
            ego_speed
        };

        let speed_diff = right_speed - ego_lane_speed;

        if speed_diff > self.config.speed_diff_threshold {
            self.lanes[2].trigger_duration += dt_secs;
        } else {
            self.lanes[2].trigger_duration = 0.0;
        }

        if self.lanes[2].trigger_duration >= self.config.hysteresis_seconds {
            vec![LaneSpeedAlert {
                speed_diff_mph: speed_diff,
                duration_secs: self.lanes[2].trigger_duration,
            }]
        } else {
            vec![]
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    /// A box with centroid near x=20 on a 1280-wide frame → left lane.
    #[test]
    fn test_lane_assignment_left() {
        let cfg = Config::default();
        let analyzer = LaneSpeedAnalyzer::new(&cfg);
        let lane = analyzer.assign_lane(&(0.0, 0.0, 40.0, 40.0));
        assert_eq!(lane, 0);
    }

    /// A box with centroid near x=900 on a 1280-wide frame → right lane.
    #[test]
    fn test_lane_assignment_right() {
        let cfg = Config::default();
        let analyzer = LaneSpeedAnalyzer::new(&cfg);
        let lane = analyzer.assign_lane(&(800.0, 0.0, 1000.0, 40.0));
        assert_eq!(lane, 2);
    }

    /// No tracks → no alerts.
    #[test]
    fn test_no_alert_when_no_tracks() {
        let cfg = Config::default();
        let mut analyzer = LaneSpeedAnalyzer::new(&cfg);
        let alerts = analyzer.analyze(&[], 60.0, 0.033);
        assert!(alerts.is_empty());
    }
}
