//! # 🚗 Lane Relative Speed Module
//!
//! Estimates relative speed of adjacent lane vehicles using camera-only
//! methods and triggers "Merge Right" reminders when the right lane
//! is moving significantly faster.
//!
//! ## Algorithm
//!
//! 1. Assign each Track to a lane (left, ego, right) via centroid x-position
//! 2. Estimate distance via pinhole model: `Z = (f * W) / w`
//! 3. Compute relative velocity from `dZ/dt`
//! 4. Low-pass filter for jitter removal
//! 5. Trigger alert after configured hysteresis period
//!
//! ## Status
//!
//! Core logic is implemented. Lane assignment uses the x-centroid of each
//! tracked bounding box, dividing the frame into three vertical strips.
//! Real-world calibration will improve lane-boundary accuracy.

use crate::config::LaneSpeedConfig;
use crate::tracking::deep_sort::Track;
use crate::utils::geometry::{compute_relative_velocity, estimate_distance, low_pass_filter};

/// An alert generated by the lane speed analyzer.
#[derive(Debug, Clone)]
pub struct LaneSpeedAlert {
    /// How many mph faster the right lane is moving.
    pub speed_diff_mph: f32,
    /// How many seconds this condition has persisted.
    pub duration_secs: f32,
}

/// Per-lane state for hysteresis tracking.
#[derive(Debug, Clone, Default)]
struct LaneState {
    /// Average speed of vehicles in this lane (mph).
    avg_speed: f32,
    /// Smoothed speed (low-pass).
    smoothed_speed: f32,
    /// Time since condition first exceeded threshold (seconds).
    trigger_duration: f32,
    /// Previous frame's distance for velocity computation.
    prev_distances: Vec<f32>,
}

/// Analyzes relative lane speeds and triggers courtesy alerts.
pub struct LaneSpeedAnalyzer {
    config: LaneSpeedConfig,
    /// Frame width — used for lane assignment.
    frame_width: f32,
    /// Known real-world width of a vehicle in meters.
    vehicle_width_m: f32,
    /// Camera focal length in pixels.
    focal_length: f32,
    /// Per-lane state (index 0=left, 1=ego, 2=right).
    lanes: [LaneState; 3],
    /// Smoothing factor for speed LPF.
    alpha: f32,
}

impl LaneSpeedAnalyzer {
    pub fn new(config: &crate::config::Config) -> Self {
        Self {
            config: config.lane_speed.clone(),
            frame_width: config.camera.frame_width as f32,
            focal_length: config.camera.focal_length,
            vehicle_width_m: 1.8,
            lanes: [LaneState::default(), LaneState::default(), LaneState::default()],
            alpha: 0.3,
        }
    }

    /// Assigns a track to a lane based on its centroid x-position.
    fn assign_lane(&self, bbox: &(f32, f32, f32, f32)) -> usize {
        let cx = (bbox.0 + bbox.2) / 2.0;
        let third = self.frame_width / 3.0;
        if cx < third {
            0 // left lane
        } else if cx < 2.0 * third {
            1 // ego lane
        } else {
            2 // right lane
        }
    }

    /// Analyzes tracked vehicles for lane speed compliance.
    ///
    /// # Arguments
    /// * `tracks`   - Active tracked objects from the tracker.
    /// * `ego_speed` - Ego-vehicle speed in mph.
    /// * `dt_secs`   - Time since last frame in seconds.
    ///
    /// # Returns
    /// Alerts when the right lane is significantly faster than ego lane.
    pub fn analyze(
        &mut self,
        tracks: &[Track],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<LaneSpeedAlert> {
        // 1. Reset per-lane accumulators.
        let mut lane_dists: [Vec<f32>; 3] = [Vec::new(), Vec::new(), Vec::new()];

        for track in tracks {
            let lane = self.assign_lane(&track.bbox);
            let pixel_width = (track.bbox.2 - track.bbox.0).abs();
            if pixel_width < 2.0 {
                continue; // too small, unreliable distance
            }

            let distance_m =
                estimate_distance(pixel_width, self.vehicle_width_m, self.focal_length);
            if distance_m < 0.5 || distance_m > 200.0 {
                continue; // outlier
            }

            lane_dists[lane].push(distance_m);
        }

        // 2. Compute average speed per lane from distance changes.
        for lane_idx in 0..3 {
            let prev = &self.lanes[lane_idx].prev_distances;
            let curr = &lane_dists[lane_idx];

            let avg_speed = if !prev.is_empty() && !curr.is_empty() && dt_secs > 0.001 {
                // Average distance change across matched pairs.
                let n = prev.len().min(curr.len());
                let total_vel: f32 = (0..n)
                    .map(|i| compute_relative_velocity(prev[i], curr[i], dt_secs))
                    .sum();
                // Convert m/s to mph (1 m/s ≈ 2.237 mph).
                let avg_vel_ms = total_vel / n as f32;
                avg_vel_ms * 2.237
            } else {
                0.0
            };

            self.lanes[lane_idx].avg_speed = avg_speed;
            self.lanes[lane_idx].smoothed_speed = low_pass_filter(
                avg_speed,
                self.lanes[lane_idx].smoothed_speed,
                self.alpha,
            );
            self.lanes[lane_idx].prev_distances = curr.clone();
        }

        // 3. Detect right-lane-faster condition.
        let mut alerts = Vec::new();
        let right_speed = self.lanes[2].smoothed_speed;
        let ego_lane_speed = if self.lanes[1].smoothed_speed.abs() > 0.1 {
            self.lanes[1].smoothed_speed
        } else {
            ego_speed // fall back to reported ego speed
        };

        let speed_diff = right_speed - ego_lane_speed;

        if speed_diff > self.config.speed_diff_threshold {
            self.lanes[2].trigger_duration += dt_secs;
        } else {
            self.lanes[2].trigger_duration = 0.0;
        }

        if self.lanes[2].trigger_duration >= self.config.hysteresis_seconds {
            alerts.push(LaneSpeedAlert {
                speed_diff_mph: speed_diff,
                duration_secs: self.lanes[2].trigger_duration,
            });
        }

        alerts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    #[test]
    fn test_lane_assignment_left() {
        let cfg = Config::default();
        let analyzer = LaneSpeedAnalyzer::new(&cfg);
        // Centroid at x≈20 → should be lane 0 (left).
        let lane = analyzer.assign_lane(&(0.0, 0.0, 40.0, 40.0));
        assert_eq!(lane, 0);
    }

    #[test]
    fn test_lane_assignment_right() {
        let cfg = Config::default();
        let analyzer = LaneSpeedAnalyzer::new(&cfg);
        // Frame width is 1280, centroid at x≈900 → lane 2 (right).
        let lane = analyzer.assign_lane(&(800.0, 0.0, 1000.0, 40.0));
        assert_eq!(lane, 2);
    }

    #[test]
    fn test_no_alert_when_no_tracks() {
        let cfg = Config::default();
        let mut analyzer = LaneSpeedAnalyzer::new(&cfg);
        let alerts = analyzer.analyze(&[], 60.0, 0.033);
        assert!(alerts.is_empty());
    }
}
