//! # 🚗 Lane Relative Speed Module
//!
//! Estimates relative speed of adjacent lane vehicles using camera-only
//! methods and triggers "Merge Right" reminders when the right lane
//! is moving significantly faster.
//!
//! ## Algorithm (planned)
//!
//! 1. Assign each Track to a lane (left, ego, right) via centroid x-position
//! 2. Estimate distance via pinhole model: `Z = (f * W) / w`
//! 3. Compute relative velocity from `dZ/dt`
//! 4. Low-pass filter for jitter removal
//! 5. Trigger alert after 3s hysteresis
//!
//! ## TODO
//!
//! - [ ] Implement lane assignment by centroid x-position
//! - [ ] Implement pinhole distance estimation
//! - [ ] Compute relative velocity with temporal smoothing
//! - [ ] Add alert hysteresis (3-second confirmation window)

#![allow(unused_variables, dead_code)]

use crate::tracking::deep_sort::Track;

/// An alert generated by the lane speed analyzer.
#[derive(Debug, Clone)]
pub struct LaneSpeedAlert {
    /// How many mph faster the right lane is moving.
    pub speed_diff_mph: f32,
    /// How many seconds this condition has persisted.
    pub duration_secs: f32,
}

/// Analyzes relative lane speeds and triggers courtesy alerts.
pub struct LaneSpeedAnalyzer {
    // TODO: config, per-lane state, hysteresis timers
}

impl LaneSpeedAnalyzer {
    pub fn new(config: &crate::config::Config) -> Self {
        todo!("Initialize lane speed analyzer from config");
    }

    /// Analyzes tracked vehicles for lane speed compliance.
    pub fn analyze(
        &mut self,
        tracks: &[Track],
        ego_speed: f32,
        dt_secs: f32,
    ) -> Vec<LaneSpeedAlert> {
        todo!("Assign lanes → estimate speeds → detect differentials");
    }
}
