//! # 🏋️ YOLO Training Orchestrator (Rust-first, Python-free CLI)
//!
//! Manages the full YOLO training lifecycle entirely from Rust.
//! The only Python dependency is `ultralytics` called via subprocess
//! on the cloud GPU VM, no Python scripts in this repo.
//!
//! ## Workflow
//!
//! 1. **`civicsense collect`**, capture frames from camera/video
//! 2. Label the images (any YOLO-format labeler, CVAT, labelImg, etc.)
//! 3. **`civicsense train prepare`**, validate structure, split train/val, generate YAML
//! 4. **`civicsense train run`**, install ultralytics (if needed), train on GPU, export ONNX
//! 5. **`civicsense train validate`**, load the exported ONNX with `ort` and verify it works
//!
//! Cross-compile the binary on your Mac for the cloud VM (`x86_64-unknown-linux-gnu`),
//! scp it up, and run `civicsense train run` on the GPU instance.

use std::path::{Path, PathBuf};

// ─────────────────────────────────────────────────────────────────────────────
//  Dataset preparation
// ─────────────────────────────────────────────────────────────────────────────

/// Describes the expected YOLO dataset layout on disk.
///
/// CivicSense expects label files in YOLO `.txt` format alongside images:
///
/// ```text
/// data/civicsense/
///   images/
///     train/
///       frame_000001.jpg
///       frame_000002.jpg
///       ...
///     val/
///       ...
///   labels/
///     train/
///       frame_000001.txt
///       frame_000002.txt
///       ...
///     val/
///       ...
/// ```
///
/// Each `.txt` file contains one line per object:
/// `class_id x_center y_center width height`
/// (normalised 0–1, space-separated).
pub struct Dataset {
    /// Root directory of the dataset.
    pub root: PathBuf,
    /// Number of classes (CivicSense = 7).
    pub num_classes: u32,
    /// Class names in order matching ModelConfig.classes.
    pub class_names: Vec<String>,
    /// Number of images in the training split.
    pub train_count: usize,
    /// Number of images in the validation split.
    pub val_count: usize,
}

impl Dataset {
    /// Scans `root` and validates the YOLO dataset structure.
    ///
    /// # Errors
    ///
    /// Returns `Err` if required directories are missing, or if any label
    /// file cannot be parsed.
    pub fn open(root: &Path) -> Result<Self, String> {
        let train_img_dir = root.join("images").join("train");
        let val_img_dir = root.join("images").join("val");
        let train_label_dir = root.join("labels").join("train");
        let val_label_dir = root.join("labels").join("val");

        let train_count = count_images(&train_img_dir)?;
        let val_count = count_images(&val_img_dir)?;

        if train_count == 0 && val_count == 0 {
            return Err(format!(
                "No images found in '{}' or '{}'",
                train_img_dir.display(),
                val_img_dir.display()
            ));
        }

        // Quick validation: spot-check that first N label files parse.
        let label_dirs = [&train_label_dir, &val_label_dir];
        for dir in &label_dirs {
            if dir.exists() {
                validate_labels(&dir)?;
            }
        }

        let class_names = vec![
            "stop_sign".into(),
            "traffic_light".into(),
            "crosswalk".into(),
            "vehicle".into(),
            "truck".into(),
            "bus".into(),
            "intersection_zone".into(),
        ];

        log::info!(
            "Dataset '{}': {} train, {} val images, {} classes",
            root.display(),
            train_count,
            val_count,
            class_names.len()
        );

        Ok(Self {
            root: root.to_path_buf(),
            num_classes: class_names.len() as u32,
            class_names,
            train_count,
            val_count,
        })
    }

    /// Writes a `dataset.yaml` file consumable by the Ultralytics `yolo` CLI.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the file cannot be written.
    pub fn write_yaml(&self, path: &Path) -> Result<(), String> {
        let root_abs = std::fs::canonicalize(&self.root)
            .map_err(|e| format!("Cannot resolve dataset root: {e}"))?;

        let mut out = String::new();
        out.push_str(&format!(
            "# CivicSense dataset (auto-generated by `civicsense train prepare`)\n"
        ));
        out.push_str(&format!("path: {}\n\n", root_abs.display()));
        out.push_str("train: images/train\n");
        out.push_str("val: images/val\n");
        out.push_str(&format!("nc: {}\n\nnames:\n", self.num_classes));
        for (i, name) in self.class_names.iter().enumerate() {
            out.push_str(&format!("  {}: {}\n", i, name));
        }

        std::fs::write(path, out)
            .map_err(|e| format!("Cannot write dataset config '{:?}': {e}", path))
    }

    /// Splits a flat directory of labelled images into train/val.
    ///
    /// Expects `source` to contain `.jpg`/`.png` files and
    /// corresponding `.txt` label files. Moves them into
    /// `root/images/{train,val}` and `root/labels/{train,val}`.
    ///
    /// # Errors
    ///
    /// Returns `Err` if I/O fails.
    pub fn split(source: &Path, root: &Path, val_fraction: f64) -> Result<Self, String> {
        use std::fs;

        let val_frac = val_fraction.clamp(0.0, 0.5);

        // Collect image files with corresponding label files.
        let mut pairs: Vec<(PathBuf, PathBuf)> = Vec::new();
        for entry in fs::read_dir(source).map_err(|e| format!("Cannot read '{:?}': {e}", source))? {
            let entry = entry.map_err(|e| format!("Read dir entry: {e}"))?;
            let path = entry.path();
            let ext = path
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or("")
                .to_lowercase();
            if !["jpg", "jpeg", "png"].contains(&ext.as_str()) {
                continue;
            }
            let label_path = path.with_extension("txt");
            if label_path.exists() {
                pairs.push((path, label_path));
            } else {
                log::warn!("Skipping '{:?}', no matching label file", path);
            }
        }

        if pairs.is_empty() {
            return Err(format!("No labelled image pairs found in '{:?}'", source));
        }

        // Shuffle deterministically (simple Fisher-Yates with fixed seed).
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};
        let seed: u64 = {
            let mut h = DefaultHasher::new();
            source.hash(&mut h);
            h.finish()
        };
        let mut rng = SimpleRng::new(seed);
        for i in (1..pairs.len()).rev() {
            let j = (rng.next() as usize) % (i + 1);
            pairs.swap(i, j);
        }

        let split_idx = (pairs.len() as f64 * (1.0 - val_frac)).ceil() as usize;
        let (train_pairs, val_pairs) = pairs.split_at(split_idx);

        // Create directory structure.
        let dirs = [
            root.join("images").join("train"),
            root.join("images").join("val"),
            root.join("labels").join("train"),
            root.join("labels").join("val"),
        ];
        for d in &dirs {
            fs::create_dir_all(d)
                .map_err(|e| format!("Cannot create '{:?}': {e}", d))?;
        }

        // Copy files (same filesystem = fast reflink copies).
        let copy_pairs = |pairs: &[(PathBuf, PathBuf)], img_dir: &Path, lbl_dir: &Path| {
            for (img_path, lbl_path) in pairs {
                let fname = img_path
                    .file_name()
                    .ok_or_else(|| "Bad filename".to_string())?;
                let dest_img = img_dir.join(fname);
                let dest_lbl = lbl_dir.join(fname).with_extension("txt");
                fs::copy(img_path, &dest_img)
                    .map_err(|e| format!("Cannot copy '{:?}' -> '{:?}': {e}", img_path, dest_img))?;
                fs::copy(lbl_path, &dest_lbl)
                    .map_err(|e| format!("Cannot copy '{:?}' -> '{:?}': {e}", lbl_path, dest_lbl))?;
            }
            Ok::<_, String>(())
        };

        copy_pairs(train_pairs, &dirs[0], &dirs[2])?;
        copy_pairs(val_pairs, &dirs[1], &dirs[3])?;

        log::info!(
            "Split {} labelled pairs into {} train + {} val (val_fraction={})",
            pairs.len(),
            train_pairs.len(),
            val_pairs.len(),
            val_frac
        );

        Self::open(root)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Subprocess training (runs `yolo` CLI via Python on the cloud GPU VM)
// ─────────────────────────────────────────────────────────────────────────────

/// Configuration for a training run.
pub struct TrainingRun {
    /// Path to the dataset YAML config.
    pub data_yaml: PathBuf,
    /// Pretrained model name or path (e.g. "yolov8n.pt").
    pub model: String,
    /// Number of epochs.
    pub epochs: u32,
    /// Batch size.
    pub batch: u32,
    /// Input image size.
    pub imgsz: u32,
    /// Output project directory.
    pub project: PathBuf,
    /// Experiment name.
    pub name: String,
    /// GPU device index (0, 1, "0,1", etc.).
    pub device: String,
}

impl TrainingRun {
    /// Executes the training by spawning the `yolo` CLI (ultralytics).
    ///
    /// This shells out to Python because no Rust-native YOLO training
    /// framework exists. The function:
    ///
    /// 1. Checks that `python3` and `ultralytics` are available.
    /// 2. Runs `yolo train ...` as a subprocess.
    /// 3. After training completes, exports to ONNX.
    /// 4. Validates the exported model with `ort` crate.
    ///
    /// # Errors
    ///
    /// Returns `Err` if Python/ultralytics is not installed, the training
    /// fails, or the exported model cannot be validated.
    pub fn run(&self) -> Result<PathBuf, String> {
        // ── 1. Check environment ─────────────────────────────────────
        log::info!("Checking Python environment...");
        let python = find_python()?;
        check_ultralytics(&python)?;

        // ── 2. Install ultralytics if missing ────────────────────────
        if !ultralytics_installed(&python)? {
            log::info!("Installing ultralytics...");
            let status = std::process::Command::new(&python)
                .args(["-m", "pip", "install", "-q", "ultralytics", "onnxsim"])
                .status()
                .map_err(|e| format!("Failed to run pip: {e}"))?;
            if !status.success() {
                return Err("pip install ultralytics failed".into());
            }
        }

        // ── 3. Train ────────────────────────────────────────────────
        let project_str = self.project.to_string_lossy().to_string();
        let data_str = self.data_yaml.to_string_lossy().to_string();

        log::info!(
            "Starting training: model={}, epochs={}, batch={}, imgsz={}, device={}",
            self.model,
            self.epochs,
            self.batch,
            self.imgsz,
            self.device,
        );

        let status = std::process::Command::new(&python)
            .args([
                "-m",
                "ultralytics",
                "yolo",
                "train",
                &format!("model={}", self.model),
                &format!("data={}", &data_str),
                &format!("epochs={}", self.epochs),
                &format!("batch={}", self.batch),
                &format!("imgsz={}", self.imgsz),
                &format!("device={}", self.device),
                &format!("project={}", &project_str),
                &format!("name={}", self.name),
                "cos_lr=True",
                "patience=50",
                "save=True",
                "val=True",
            ])
            .status()
            .map_err(|e| format!("Failed to launch training: {e}"))?;

        if !status.success() {
            return Err(format!("Training failed (exit code: {:?})", status.code()));
        }

        let best_pt = self
            .project
            .join(&self.name)
            .join("weights")
            .join("best.pt");
        log::info!("Training complete. Best weights: {:?}", best_pt);

        // ── 4. Export to ONNX ───────────────────────────────────────
        let onnx_path = best_pt.with_extension("onnx");
        log::info!("Exporting to ONNX: {:?}", onnx_path);

        let export_status = std::process::Command::new(&python)
            .args([
                "-m",
                "ultralytics",
                "yolo",
                "export",
                &format!("model={}", best_pt.to_string_lossy()),
                "format=onnx",
                &format!("imgsz={}", self.imgsz),
                "half=False",
            ])
            .status()
            .map_err(|e| format!("Failed to export ONNX: {e}"))?;

        if !export_status.success() {
            return Err(format!("ONNX export failed (exit code: {:?})", export_status.code()));
        }

        // ── 5. Validate ONNX with `ort` ─────────────────────────────
        log::info!("Validating ONNX model with ort...");
        validate_onnx(&onnx_path)?;

        log::info!("✅ Training pipeline complete. Model at {:?}", onnx_path);
        Ok(onnx_path)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  ONNX validation via `ort`
// ─────────────────────────────────────────────────────────────────────────────

/// Loads an ONNX model with `ort` and runs a quick forward pass with a
/// dummy tensor to verify it works.
pub fn validate_onnx(path: &Path) -> Result<(), String> {
    if !path.exists() {
        return Err(format!("ONNX model not found: {:?}", path));
    }

    let mut session = ort::session::Session::builder()
        .map_err(|e| format!("ort init: {e}"))?
        .commit_from_file(path)
        .map_err(|e| format!("Failed to load ONNX '{:?}': {e}", path))?;

    // YOLO expects [1, 3, 640, 640] input. Build a dummy tensor.
    let input_shape = (1usize, 3usize, 640usize, 640usize);
    log::info!("ONNX model input shape: {:?}", input_shape);

    let total_elts: usize = input_shape.0 * input_shape.1 * input_shape.2 * input_shape.3;
    let dummy = vec![0.0f32; total_elts];

    let array = ndarray::Array4::from_shape_vec(input_shape, dummy)
        .map_err(|e| format!("Dummy tensor shape: {e}"))?;

    let tensor = ort::value::Tensor::from_array(array)
        .map_err(|e| format!("Tensor from array: {e}"))?;

    let _outputs = session
        .run(ort::inputs![tensor])
        .map_err(|e| format!("Inference on dummy input failed: {e}"))?;

    log::info!("✅ ONNX model validated successfully (forward pass OK)");
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Count image files in a directory (recursive).
fn count_images(dir: &Path) -> Result<usize, String> {
    if !dir.exists() {
        return Ok(0);
    }
    let mut count = 0;
    for entry in std::fs::read_dir(dir).map_err(|e| format!("Cannot read '{:?}': {e}", dir))? {
        let entry = entry.map_err(|e| format!("Read entry: {e}"))?;
        let ext = entry
            .path()
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("")
            .to_lowercase();
        if ["jpg", "jpeg", "png", "bmp"].contains(&ext.as_str()) {
            count += 1;
        }
    }
    Ok(count)
}

/// Spot-check label files in a directory, each line must parse as 5 floats.
fn validate_labels(dir: &Path) -> Result<(), String> {
    for entry in std::fs::read_dir(dir).map_err(|e| format!("Cannot read '{:?}': {e}", dir))? {
        let entry = entry.map_err(|e| format!("Read entry: {e}"))?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        let content =
            std::fs::read_to_string(&path).map_err(|e| format!("Cannot read '{:?}': {e}", path))?;
        for (lineno, line) in content.lines().enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() != 5 {
                return Err(format!(
                    "'{:?}' line {}: expected 5 fields, got {}",
                    path,
                    lineno + 1,
                    parts.len()
                ));
            }
            for (i, p) in parts.iter().enumerate() {
                p.parse::<f32>()
                    .map_err(|_| format!("'{:?}' line {} field {}: not a float", path, lineno + 1, i + 1))?;
            }
        }
    }
    Ok(())
}

/// Find a working Python 3 interpreter.
fn find_python() -> Result<String, String> {
    for candidate in &["python3", "python"] {
        let output = std::process::Command::new(candidate)
            .arg("--version")
            .output();
        if let Ok(out) = output {
            if out.status.success() {
                return Ok(candidate.to_string());
            }
        }
    }
    Err("No Python 3 interpreter found. Install Python 3 on the cloud GPU VM.".into())
}

/// Check if ultralytics is importable.
fn check_ultralytics(python: &str) -> Result<(), String> {
    let output = std::process::Command::new(python)
        .args(["-c", "import ultralytics; print(ultralytics.__version__)"])
        .output()
        .map_err(|e| format!("Failed to check ultralytics: {e}"))?;

    if output.status.success() {
        let version = String::from_utf8_lossy(&output.stdout).trim().to_string();
        log::info!("ultralytics {} found", version);
        Ok(())
    } else {
        log::warn!("ultralytics not found. Will install automatically.");
        Ok(())
    }
}

/// Check if ultralytics is installed (returns false if not).
fn ultralytics_installed(python: &str) -> Result<bool, String> {
    let output = std::process::Command::new(python)
        .args(["-c", "import ultralytics"])
        .output()
        .map_err(|e| format!("Failed to check ultralytics: {e}"))?;
    Ok(output.status.success())
}

// ─────────────────────────────────────────────────────────────────────────────
//  Minimal deterministic PRNG (for reproducible shuffle)
// ─────────────────────────────────────────────────────────────────────────────

struct SimpleRng(u64);

impl SimpleRng {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn create_test_dataset(dir: &Path) {
        let img_dir = dir.join("images").join("train");
        let lbl_dir = dir.join("labels").join("train");
        fs::create_dir_all(&img_dir).unwrap();
        fs::create_dir_all(&lbl_dir).unwrap();

        // Create one dummy image and label.
        let img_path = img_dir.join("test_000001.jpg");
        let img = image::RgbImage::new(100, 100);
        img.save(&img_path).unwrap();

        let lbl_path = lbl_dir.join("test_000001.txt");
        fs::write(&lbl_path, "0 0.5 0.5 0.2 0.2\n3 0.8 0.5 0.3 0.3\n").unwrap();
    }

    #[test]
    fn test_dataset_open_valid() {
        let dir = std::env::temp_dir().join("civicsense_test_open");
        let _ = fs::remove_dir_all(&dir);
        create_test_dataset(&dir);

        let ds = Dataset::open(&dir).expect("Dataset should open");
        assert_eq!(ds.train_count, 1);
        assert_eq!(ds.val_count, 0);
        assert_eq!(ds.num_classes, 7);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_dataset_open_missing_root() {
        let result = Dataset::open(Path::new("/nonexistent/path"));
        assert!(result.is_err());
    }

    #[test]
    fn test_dataset_yaml_generation() {
        let dir = std::env::temp_dir().join("civicsense_test_yaml");
        let _ = fs::remove_dir_all(&dir);
        create_test_dataset(&dir);
        let ds = Dataset::open(&dir).unwrap();

        let yaml_path = dir.join("dataset.yaml");
        ds.write_yaml(&yaml_path).unwrap();

        let content = fs::read_to_string(&yaml_path).unwrap();
        assert!(content.contains("nc: 7"));
        assert!(content.contains("stop_sign"));
        assert!(content.contains("intersection_zone"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_labels_valid() {
        let dir = std::env::temp_dir().join("civicsense_test_labels");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let lbl_path = dir.join("test.txt");
        fs::write(&lbl_path, "0 0.5 0.5 0.2 0.2\n3 0.8 0.5 0.3 0.3\n").unwrap();
        // Should not panic.
        validate_labels(&dir).unwrap();

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_labels_invalid() {
        let dir = std::env::temp_dir().join("civicsense_test_bad_labels");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let lbl_path = dir.join("bad.txt");
        fs::write(&lbl_path, "0 0.5 0.5 0.2\n").unwrap(); // only 4 fields
        assert!(validate_labels(&dir).is_err());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_label_validate_with_missing_file_not_crashing() {
        // Non-existent dir should not crash (read_dir will error).
        let result = validate_labels(Path::new("/tmp/nonexistent_labels_xyz"));
        assert!(result.is_err());
    }

    #[test]
    fn test_split_creates_train_val() {
        let source = std::env::temp_dir().join("civicsense_test_split_source");
        let dest = std::env::temp_dir().join("civicsense_test_split_dest");
        let _ = fs::remove_dir_all(&source);
        let _ = fs::remove_dir_all(&dest);
        fs::create_dir_all(&source).unwrap();

        // Create 6 labelled image pairs.
        for i in 1..=6 {
            let img_path = source.join(format!("frame_{:06}.jpg", i));
            let img = image::RgbImage::new(100, 100);
            img.save(&img_path).unwrap();
            let lbl_path = source.join(format!("frame_{:06}.txt", i));
            fs::write(&lbl_path, "0 0.5 0.5 0.2 0.2\n").unwrap();
        }

        let ds = Dataset::split(&source, &dest, 0.2).expect("Split should work");
        assert_eq!(ds.train_count + ds.val_count, 6);

        let _ = fs::remove_dir_all(&source);
        let _ = fs::remove_dir_all(&dest);
    }
}
